### PR TITLE
Inputs_for for liveview

### PR DESCRIPTION
**Pull request by woylie**
This adds `polymorphic_embed_inputs_for/3` for LiveView integration. The difference is that it doesn't use an anonymous function, and it doesn't automatically render hidden inputs. This follows the example of `Phoenix.HTML.Form.inputs_for/3`.

I also handled some warnings and updated mix.lock.

### CODE REVIEW

**Comment by woylie** [comment]
I put this back to draft because I'd like to change one thing. When rendering forms for polymorphic data types, especially in LiveView, a common use case would be a form in which you can dynamically add more entries and select the concrete type for each of those entries. This is not possible with the current `polymorphic_embed_inputs_for/4` function, since it requires you to pass the type identifier.

For the new `polymorphic_embed_inputs_for/3` function, I would prefer to pass the schema instead, so that the function can determine the type automatically from the data or the parameters. Therefore, I'd like to add a `get_polymorphic_type/3` function to the Html module, which takes the form, schema and field as parameters.

**Comment by woylie** [comment]
I made the described updates.

- `PolymorphicEmbed.HTML.Form.get_polymorphic_type(form, schema, field)`
- `PolymorphicEmbed.HTML.Form.polymorphic_embed_inputs_for(form, field)`

Please have a look.

**Comment by mathieuprog** [comment]
Great work @woylie ! Sorry but I've been away from Elixir for some time, it's been a looong looong time 😰

You confused me with something now, you're not passing the `type` at all (as opposed to the existing `polymorphic_embed_inputs_for/4`).

Do we even need the type at all even for the existing function? Does it have any use for any case? (again, been a long time, might miss something obvious 😂).

**Comment by woylie** [comment]
> Great work @woylie ! Sorry but I've been away from Elixir for some time, it's been a looong looong time 😰
> 
> You confused me with something now, you're not passing the `type` at all (as opposed to the existing `polymorphic_embed_inputs_for/4`).
> 
> Do we even need the type at all even for the existing function? Does it have any use for any case? (again, been a long time, might miss something obvious 😂).

Hi @mathieuprog! Before this PR, the library didn't have a function for determining the type automatically, and that's why it has to be passed to the old `polymorphic_embed_inputs_for/4`. We can change the existing function to use the new `get_polymorphic_type/3` function, of course, and remove the type argument. I just didn't want to introduce any breaking changes in this PR.

**Comment by mathieuprog** [comment]
Could you add that change? I will just release a major version as there is a breaking change.

**Comment by woylie** [comment]
Sure!

**Comment by woylie** [comment]
When I just remove the `type` parameter from `polymorphic_embed_inputs_for/4`, all tests pass except for `form with polymorphic embed to nil`. The `channel` value is `nil` in that test, which of course means there is no data from which we can derive the type. The previous implementation would just return empty inputs for the type that was passed to the function.

For the new `polymorphic_embed_inputs_for/3` function, we can change it to not render any inputs if the polymorphic field is `nil`. If you want to initialize the form with empty inputs of a certain type, you can still initialize the changeset that way.

We can also keep the `/4` version of the function additionally to the new `/3` version, but I don't find it very useful in the first place, to be honest.

**Comment by mathieuprog** [comment]
> If you want to initialize the form with empty inputs of a certain type, you can still initialize the changeset that way.
Which way?

**Comment by mathieuprog** [comment]
I realize my own app depends on these empty fields lol. So keep the /4, add the /3. And I'll see with my own app how I should refactor it to only use /3, or we just keep /4 if the code is easier for getting these empty fields.

**Comment by woylie** [comment]
> I realize my own app depends on these empty fields lol. So keep the /4, add the /3. And I'll see with my own app how I should refactor it to only use /3, or we just keep /4 if the code is easier for getting these empty fields.

I see. We're initializing the changeset as described in our application to get those empty fields (did I mention you can do that? 😅 ).

I'll update the PR to include both variants, and you can decide whether you want to deprecate `/4` at some point.

**Comment by mathieuprog** [comment]
Yep just keep the /4 for now and I'll try your suggestion in my app! I'll merge your PR in master as soon as it is ready. Can you comment here when it's ready for merge? Thanks!

**Comment by woylie** [comment]
Ok, I updated the PR. I replaced the `polymorphic?` variable in the tests with a `generator` variable to switch between the three functions in `safe_inputs_for`.

**Comment by woylie** [comment]
It runs the same tests on both of the `polymorphic_embed_inputs_for` functions, one time with the given type and one time with the automatically determined type. I think that's fine, and the test suite doesn't take long anyway? If you decide to remove the older function in the future, you can just remove it from the generator list.

**Comment by mathieuprog** [comment]
Could you tell me why you decided that `polymorphic_embed_inputs_for/3` doesn't render the hidden input fields?

**Comment by mathieuprog** [comment]
1.10.0 has been released but major update coming 2.0.0 coming tomorrow :D

**Comment by mathieuprog** [comment]
Btw you change

`type_name |> to_string()` to
`to_string(type_name)`
removing the pipe.

`Keyword.get(type_opts, :identify_by_fields, []) |> Enum.map(&to_string/1)` to
`type_opts |> Keyword.get(:identify_by_fields, []) |> Enum.map(&to_string/1)`
adding the pipe.


Do you have any rule you made for yourself?

**Comment by woylie** [comment]
Those are two rules that Credo has checks for:

- single pipe (https://github.com/rrrene/credo/blob/master/lib/credo/check/readability/single_pipe.ex#L8)
- pipe chain start (https://github.com/rrrene/credo/blob/master/lib/credo/check/refactor/pipe_chain_start.ex#L10)

I find both reasonable and usually have them enabled in my projects.

**Comment by mathieuprog** [comment]
https://elixirforum.com/t/polymorphic-embeds-in-ecto/31951/9

**Comment by mathieuprog** [comment]
Hello @woylie 
I can't make this work with LiveView 0.18
Could you have a look please? I'm not experienced enough with LV.

**Comment by woylie** [comment]
@mathieuprog I'll check tomorrow.

**Comment by mathieuprog** [comment]
Ty! The error I'm having when upgrading to 0.18 is the following:

> == Compilation error in file test/polymorphic_embed_test.exs ==
** (CompileError) test/polymorphic_embed_test.exs:2158: undefined function sigil_H/2
    (elixir 1.12.3) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
    
This is really a mystery for me.

**Comment by woylie** [comment]
Ah, that's easy, a bunch of functions were moved from `Phoenix.LiveView.Helpers` to `Phoenix.Component`, including that sigil. If you update the `import` accordingly, it should work.

**Comment by mathieuprog** [comment]
In the docs the example says to use:
```elixir
use Phoenix.Component
```
https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#sigil_H/2

However an `import` works...

**Comment by woylie** [comment]
`__using__` does a little bit more. You need to `use` the module in order to use declarative assign. But here, we only need to import the sigil, so `import` should be fine.

**Comment by mathieuprog** [comment]
@woylie I only noticed there were some inconsistencies in that PR following this open issue:
https://github.com/mathieuprog/polymorphic_embed/issues/63

I had to remove these clauses:
```elixir
%{"__type__" => type} ->
  maybe_to_existing_atom(type)

%{__type__: type} ->
  maybe_to_existing_atom(type)
```
https://github.com/mathieuprog/polymorphic_embed/commit/7939f1c4b0dcdc0f51706ed5c7a35c4c9237ae26

The issue is still open and waiting for feedback to add the right test.

Just FYI

**Comment by woylie** [comment]
I'll have to have a look at the application where we first added that, I don't remember why this was added.

**Comment by mathieuprog** [comment]
Ok note that there is a custom type field for `:channel`:
https://github.com/mathieuprog/polymorphic_embed/blob/v3.0.5/test/support/models/polymorphic/reminder.ex#L20
And that was the source of the errors where the tests didn't take that into account.
You can see in the commit above that I replaced `__type__` by the custom field name, and the tests run successfully when removing the clauses above.

**Comment by woylie** [comment]
After upgrading to 3.0.5, `get_polymorphic_type/3` returns `nil` in our application, which then breaks the form. We don't set the `type_field` option. I guess we'll first need to check whether `type_field` is set, and if not, fall back to the stuff you removed? I can try to write tests for that, but I'm not sure whether I can get to that today.

**Comment by mathieuprog** [comment]
I'm sorry, on the other hand, nice that we have a failing case. I suspected it hence I reach out to you immediately so that we can fix it.

I would say, just add the failing test, and I'll code the fix. I'm not an active user of LiveView, I don't grasp or fully remember the case we're talking about it, so it would be nice to have an example that fails in the test.

**Comment by mathieuprog** [comment]
Most likely we should use the already existing function `get_polymorphic_module(schema, field, type_or_data)` where `type_or_data` can be that map. This gives the right module and then we can call `get_polymorphic_type(schema, field, module_or_struct)`. Seems easy once we have the failing test.
